### ISSUE TITLE
Object moved

### ISSUE THREAD

**Issue by splatigo** [aksalj/pesapaljs#12]
Hello, what could this error be implying, all was fine a while a go, but it started recently. Thanks
{ response:
   { headers:
      { 'cache-control': 'private',
        'content-type': 'text/html; charset=utf-8',
        location: 'https://demo.pesapal.com/api/postpesapaldirectorderv4/postpay
ment',
        server: 'Pesapal Server',
        'x-powered-by': 'Pesapal Api 3.0 - Rahisi, ASP.NET',
        date: 'Sun, 11 Sep 2016 17:52:54 GMT',
        'content-length': '182' },
     statusCode: 302,
     body: '<html><head><title>Object moved</title></head><body>\r\n<h2>Object m
oved to <a href="https://demo.pesapal.com/api/postpesapaldirectorderv4/postpayme
nt">here</a>.</h2>\r\n</body></html>\r\n' } }

TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at Object.urlParse [as parse] (url.js:101:5)
    at Request.parseResponse [as _callback] (D:\Software\Unpacked\tickets\node_m
odules\pesapaljs\lib\internal\core.js:305:23)
    at Request.self.callback (D:\Software\Unpacked\tickets\node_modules\pesapalj
s\node_modules\request\request.js:237:22)
    at Request.EventEmitter.emit (events.js:117:20)
    at Request.<anonymous> (D:\Software\Unpacked\tickets\node_modules\pesapaljs\
node_modules\request\request.js:1146:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\Software\Unpacked\tickets\node_modules\pe
sapaljs\node_modules\request\request.js:1097:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16

**Comment by aksalj** [comment]
Pesapal appears to be redirecting http to https now on `demo.pesapal.com`. Sending a fix...
